type Query {
    orders: [Order]
}

type Order {
    id: ID
    books: [OrderedBook]
    author: Author
}

type Author {
    id: ID
    username: String 
    age: Int
}

type OrderedBook {
    id: ID
    title: String
}